version: "3"
services:
  mushroom-server:
    image: mushroom/server
    environment:
      - DATABASE_URL=postgres://mushroom:P@ssW0rd_!@mushroom-db/mushroom_db
  mushroom-db:
    image: postgres
    environment:
      - POSTGRES_DB=mushroom_db
      - POSTGRES_USER=mushroom
      - POSTGRES_PASSWORD=P@ssW0rd_!
    ports:
      - 5432:5432
  mushroom-nginx:
    image: mushroom/nginx
    ports:
      - 443:443
    environment:
      - NGINX_UPSTREAM_HOST=http://mushroom-server:5000
      - NGINX_TIMEOUT=60
